### ISSUE TITLE
新版本真好。

### ISSUE THREAD

**Issue by houxiren** [sxzxs/cherry-snippet#1]
刚想在SUPER那边反馈，有没有可能改进命令编辑器，就看到这个引入 Cherrytree 的版本。真好。辛苦了。
1，可否如 SUPER 一样支持直接搜索中文呢？
2，原 SUPER 的 超级命令.xml 怎么快递的导入到 cherry-snippet 里面。
谢谢。

**Comment by sxzxs** [comment]
可以搜索，默认 ctrl+c 在 cherrytree跳转， 双击和ctrl+e快速编辑
最新super版本，f4可以导出到文件夹，通过cherrytree可以导入

**Comment by houxiren** [comment]
1，用拼音可以搜索，比如 “xialacaidan”，用“下拉菜单”搜不到。
2，导入，最新版 0.99.51 有BUG，一导入就崩溃，旧版的 0.39.4 可以。

**Comment by sxzxs** [comment]
修改 cherry-snippet.ahk        
搜索 str := py_all py_init
改成 str .= py_all py_init
后续我再更新

**Comment by houxiren** [comment]
可以用了，感谢！！~~
