### ISSUE TITLE
运行命令报错

### ISSUE THREAD

**Issue by houxiren** [sxzxs/cherry-snippet#2]
新建批处理节点，内容如下
:: bat
echo 测试
pause

1，新建节点时，如果选择节点类型为富文本，cherry-snippet 搜索到这个节点后执行会报错。
2，新建节点时，如果选择节点类型为纯文本，cherry-snippet 搜索到这个节点后执行，可以执行。但中文乱码。
>锘?:bat
文件名、目录名或卷标语法不正确。
>echo 娴嬭瘯
娴嬭瘯
3，python 和 AHK 未试。

**Comment by sxzxs** [comment]
加我qq吧，2397633100
