### ISSUE TITLE
是否可以设置enter发送文本到窗口？

### ISSUE THREAD

**Issue by Autumn-one** [sxzxs/cherry-snippet#7]
hook输入模式无法通过中文输入，这个不知从技术上是否可以支持？
在普通搜索模式中，我更多使用的功能是发送文本到窗口，ctrl + enter 按起来没有 enter来的舒服，是否可以更改掉这个设定？

**Comment by sxzxs** [comment]
hook模式不能用中文输入，因为不是编辑框。
这个版本不打算维护了，可以使用v2版本
enter目前是代码写死的，后续改成配置
